name: Continuous Integration

on: push

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.11.0'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: |
          echo ${{ github.ref }}
          npm run test

#      - name: Setup LCOV
#        uses: hrishikesh-kadam/setup-lcov@v1
#
#      - name: Report code coverage
#        uses: zgosalvez/github-actions-report-lcov@v3
#        with:
#          coverage-files: coverage/app/lcov.*.info
#          minimum-coverage: 90
#          artifact-name: code-coverage-report
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          working-directory: .
#          update-comment: true
